export const LEVEL_COUNT = 50;

export interface LevelEntry {
  title: string;
  lines: string[];
  skippable?: boolean;   // defaults to true if omitted
}

export const LEVEL_DATA: LevelEntry[] = [
  { title: "Q1",  lines: ["Hello, candidate. Please enter your name below."] },
  { title: "Q2",  lines: ["Accept the terms to proceed.", "Read carefully. Every word matters."] },
  { title: "Q3",  lines: ["Click the dot"] },
  { title: "Q4",  lines: ["CLICK IT! CLICK IT!! CLICK IT... WHAT ARE YOU WAITING FOR?! CLICK IT CLICK IT CLICK IT!!! GO GO GO!! CLICK. IT. NOW!!!"] },
  { title: "Q5",  lines: ["I don't know if THAT button wants to be clicked"] },
  { title: "Q6",  lines: ["A brief intermission, candidate.", "Defeat Frodrick Rederer to proceed."] },
  { title: "Q7",  lines: ["I think we are counting something here?"] },
  { title: "Q8",  lines: ["An unregistered individual has approached you during the examination.", "This interaction is not part of the official assessment."], skippable: false },
  { title: "Q9",  lines: ["Focus, candidate. Show all work.", "Select the correct answer from the options above."] },
  { title: "Q10", lines: ["Navigate to the exit.", "The path is yours to find."] },
  { title: "Q11", lines: ["A compliance section. Read every line — what matters is never where you expect it.", "Is that ink smudged... or is something hidden in the text?"] },
  { title: "Q12", lines: ["Don't read what it says. See what it is.", "Trust your eyes over the words, candidate."] },
  { title: "Q13", lines: ["Count carefully. The obvious answer is rarely the whole answer.", "Look again — you always miss the small ones."] },
  { title: "Q14", lines: ["The display is faulting again. ...gnimoc s'tahw daer t'nac uoY", "Try seeing it the other way around."] },
  { title: "Q15", lines: ["You will not find the exit in here.", "The name of this whole exam has been the hint all along."] },
  { title: "Q16", lines: ["Pick the right one. ...Look — between us — it's the BLUE one.", "I'm not supposed to help. But the system's glitching, so who's counting."] },
  { title: "Q17", lines: ["QUICK! The clock is running — you have to do something!", "...or do you? Not every alarm needs answering, candidate."] },
  { title: "Q18", lines: ["Simple arithmetic. One plus one.", "...assuming you and the machine agree on what the digits mean. Read the fine print."] },
  { title: "Q19", lines: ["Continue the pattern. It is not what it looks like.", "Say them out loud, candidate."] },
  { title: "Q20", lines: ["SYSTEM BREACH. Something is forcing its way into the exam.", "He's coming back. There's only one way out — and it's the rule they told you never to break."] },
  { title: "Q21", lines: ["He is back.", "Frodrick seems to have trained a lot...", "maybe this time you need to cheat on the exam for once???"] },
  { title: "Q22", lines: ["did you catch that??"] },
  { title: "Q23", lines: ["Corporate wanted a question that assessed your logic in math form.", "I hope you remember how to fill out a truth table..."] },
  { title: "Q24", lines: ["This should be an easy one..."] },
  { title: "Q25", lines: ["Some walls are only visible under the right conditions.", "Toggle your perspective to navigate."] },
  { title: "Q26", lines: ["A simple test of focus. Watch the panels, then repeat the pattern.", "Corporate insists on measuring 'attention to detail.'"] },
  { title: "Q27", lines: ["Reflexes count too. Stop the marker in the green.", "Don't overthink this one, candidate."] },
  { title: "Q28", lines: ["Just press submit and we can move on.", "...it seems the button has other ideas. Back it into a corner."] },
  { title: "Q29", lines: ["Order of operations. Multiplication does not wait its turn.", "No calculators, no shortcuts."] },
  { title: "Q30", lines: ["Checkpoint — halfway through your certification.", "Quick: were you actually listening to me earlier?"] },
  { title: "Q31", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q32", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q33", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q34", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q35", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q36", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q37", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q38", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q39", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q40", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q41", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q42", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q43", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q44", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q45", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q46", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q47", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q48", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q49", lines: ["The exam is still compiling this question.", "Hold tight, candidate."] },
  { title: "Q50", lines: ["One final question, candidate. You have earned it.", "Think back to the very beginning."] },
];
